### PR TITLE
Master

### PR DESCRIPTION
**Pull request by phuocle**
:)

### CODE REVIEW

**Comment by phuocle** [comment]
image

image

**Comment by phuocle** [comment]
Hi @DigitalFlow ,

Please help to check this PR

**Comment by DigitalFlow** [comment]
Hi @phuocle,

thanks for your contribution and sorry for the long delay.
I'll extend the code to allow dashboards being able to be added to solutions as well and release a new version soon.

Kind Regards,
Florian

**Comment by phuocle** [comment]
Thanks.

Some project need translate dasboard.

Will update your solution now.

**Pull request merged**
