### PR TITLE
Master

### PR DESCRIPTION
**Pull request by phuocle**
:)

### CODE REVIEW

**Comment by DigitalFlow** [comment]
Hi @phuocle,

wow, thanks a lot :)
I'll deploy this to my development environment tomorrow and give it a spin.
When it works without issues, I'll publish an update asap.

Kind Regards,
Florian

**Comment by phuocle** [comment]
working on Dashboard. Will send PR soon.

**Comment by DigitalFlow** [comment]
@phuocle
Is this PR in here not already done? What will be contained in the new PR?

**Comment by DigitalFlow** [comment]
@phuocle 
I tested it and it works as expected, thanks a lot :)
Released as v3.5.0.

**Pull request merged**
